name: employee_admin_dashboard
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  path_provider: ^2.1.0 
  
  # State Management
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  
  # Navigation
  go_router: ^16.2.1
  
  # Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.9.0  # FIXED VERSION
  
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  freezed_annotation: ^2.4.1
  
  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.3.2
  dartz: ^0.10.1
  url_strategy: ^0.3.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation - UPDATED VERSIONS
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0

  retrofit_generator: ^8.0.6
  json_serializable: ^6.8.0  # FIXED VERSION
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

